name: FlockMarket
version: 1.0
main: com.birdflop.FlockMarket
api-version: 1.16
depend: [Vault]
commands:
  deposit_item:
    description: Deposits an item into the virtual market account.
    usage: /<command> <item> <quantity>
    permission: flockmarket.deposit_item
  withdraw_item:
    description: Withdraws an item from the virtual market account.
    usage: /<command> <item> <quantity>
    permission: flockmarket.withdraw_item
  deposit_money:
    description: Deposits money into the virtual market account.
    usage: /<command> <amount>
    permission: flockmarket.deposit_money
  withdraw_money:
    description: Withdraws money from the virtual market account.
    usage: /<command> <amount>
    permission: flockmarket.withdraw_money
  market_balance:
    description: Displays the current balance of the virtual market account.
    usage: /<command>
    permission: flockmarket.market_balance
permissions:
  flockmarket.deposit_item:
    description: Allows the player to deposit items into the virtual market account.
    default: true
  flockmarket.withdraw_item:
    description: Allows the player to withdraw items from the virtual market account.
    default: true
  flockmarket.deposit_money:
    description: Allows the player to deposit money into the virtual market account.
    default: true
  flockmarket.withdraw_money:
    description: Allows the player to withdraw money from the virtual market account.
    default: true
  flockmarket.market_balance:
    description: Allows the player to view the current balance of the virtual market account.
    default: true
  